spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
    topics:
      stats:
        user-action:
          v1: telemetry.hubs.v1
        events-similarity:
          v1: telemetry.sensors.v1

server:
  port: 9096


grpc:
  server:
    port: 0